feat/hero
IT-Adventura/cacti-fe pull request #3
Opened 2024-03-28 17:55 UTC by zim89

2024-03-28 19:02 UTC, SalOne22 requested changes
Have a couple of suggestions. Also move images to assets, to satisfy linter you can reexport them in index.ts

2024-03-28 19:02 UTC, vlad-salone commented on .gitignore
> +```
What does three backticks do?

2024-03-28 19:02 UTC, vlad-salone commented on src/pages/home/ui/hero.tsx
> +          <Image
Can you rewrite it using picture component? Here is reference - https://nextjs.org/docs/app/api-reference/components/image#art-direction

2024-03-28 19:02 UTC, vlad-salone commented on src/pages/home/ui/hero.tsx
> +          <Image
Also create Picture component in shared

2024-03-28 19:02 UTC, SalOne22 commented on src/pages/home/ui/hero.tsx
> +          <div className='absolute inset-x-0 top-[190px] px-4 md:top-[186px] md:pl-8 md:pr-[146px] lg:px-[100px] xl:pr-[358px] 2xl:pl-[156px] 2xl:pr-[462px]'>
instead of pixels better use rem's

2024-03-28 19:02 UTC, SalOne22 commented on .prettierrc
> +  "jsxSingleQuote": true,
If you add formatting rule, please format all other components, or undo this change

2024-03-28 19:04 UTC, zim89 commented on .gitignore
> +```
игнорит папки, которые создаются в проекте IDE-шками WebStorm (.idea) и VS Code (.vscode)

2024-03-28 19:12 UTC, SalOne22 commented on .gitignore
> +```
> игнорит папки, которые создаются в проекте IDE-шками WebStorm (.idea) и VS Code (.vscode)

Я про ```

2024-03-28 19:14 UTC, zim89 commented on .gitignore
> +```
не обратил внимание, наверное копилот создал, а я не увидел

2024-03-28 19:30 UTC, zim89 commented on src/pages/home/ui/hero.tsx
> +          <Image
Зачем создавать в shared компонент Picture? или ты имеешь в виду сделать универсальным его? аля передаем пропсы и он рендерит Picture?

2024-03-28 20:12 UTC, SalOne22 commented on src/pages/home/ui/hero.tsx
> +          <Image
Да

2024-03-28 22:42 UTC, zim89 commented on src/pages/home/ui/hero.tsx
> +          <Image
в общем ... не смог придумать как Picture сделать универсальным общим компонентом, посему только rewrite it using picture component in hero

2024-03-29 09:19 UTC, SalOne22 commented on src/pages/home/ui/hero.tsx
> +          <Image
Окей, я тогда сам сделаю Picture компонент и заменю этот

2024-03-29 21:20 UTC, SalOne22 approved these changes

2024-03-29 21:21 UTC, merged